
logging:
  level:
    com:
      example:
        springbootsoapwsexample: TRACE
    org:
      springframework: TRACE
spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.23.129:1521:cdb1
    username: c##annv
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
